import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { StoreProvider } from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <div className="flex items-center justify-start bg-purple-800 text-white p-4 gap-4 uppercase">
            <Link className="font-semibold text-xl" href={'/calendar'}>رزور وقت</Link>
            <Link className="font-semibold text-xl" href={'/grid'}>برنامه زمانی</Link>
          </div>
          <section className="p-5">
            {children}
          </section>
        </StoreProvider>
      </body>
    </html>
  );
}
