import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center justify-end bg-purple-800 text-white p-4 gap-4 uppercase">
          <Link href={'/'}>start</Link>
          <Link href={'/calendar'}>Calendar</Link>
          <Link href={'/grid'}>grid</Link>
          </div>
          <section className="p-5">
        {children}
        </section>
      </body>
    </html>
  );
}
